### ISSUE TITLE
Transferring and adapting existing tutorials into Thimble

### ISSUE THREAD

**Issue by mickfuzz** [webgameclubs/edlab-gamemakers-club#13]
One thing that needs to be done is to take some of the great web game tutorials at sites like this one - https://phaser.io/learn

And try to bring them into an easily remixable format like this one - https://thimbleprojects.org/piratepete/334344/

The process would involve contacting the original authors to check they are supportive. And then adding the code into Thimble in a way that is easy to read and alter for learners. If you can identify a tutorial and adopt it for this process please do comment here.

**Comment by mickfuzz** [comment]
You can see our evolving guidelines for creating starter games here. 
https://github.com/webgameclubs/mozilla-webgame-clubs/blob/master/CONTRIBUTING.md#guidelines-for-contributing-games

**Comment by nkindi** [comment]
Thank you Mickfuzz for the links it's more helpful, now i can get a sens of where to start

and i have a question, we have only to take those games find on phaser.io/learn or we can also work on others like ones in scratch tutorials
Thank you

**Comment by mickfuzz** [comment]
hi nkindi  - sorry to only just see your comment. 
Both of those options are great!

I've found a good list of games here too. 
https://jojoee.github.io/phaser-examples/games/

**Comment by mickfuzz** [comment]
closed as per #19
