### ISSUE TITLE
Need pipeline from GitHub to CodePen

### ISSUE THREAD

**Issue by davegoopot** [webgameclubs/edlab-gamemakers-club#18]
The purpose of GitHub is to provide source code management. The purpose of CodePen (and equivalents) is to provide an interactive coding environment for learning sessions.

We need pipeline that takes us from making an update in GitHub to an updated CodePen enviroment.

**Comment by mickfuzz** [comment]
This is a good question as I would like to involve MMU game dev students in this project. It also asks the question how are contributors likely to be developing game tutorials or remixable mini games.
The reason being is to imagine that a likely workflow / pipeline for contribution to this project that isn't too taxing for contributors. 
But also I realise it could different stroke for different folks, 

For me I have been testing things out exclusively on code playgrounds Codepen / Thimble - and then making an archive to put into github (rather that the other way around). 

How about you @davegoopot  ? What's your workflow and what would you recommend to others?

**Comment by davegoopot** [comment]
@mickfuzz I come at it from the old-school coder angle of it all starts with the source control. I think what we really need is the ability to round trip:

A. Changes in GitHub can be automatically built into a CodePen game
B. Having changed CodePen be able to create a patch to be applied back into GitHub

I'm working on A. at the moment. https://davepotts.software/2018/08/18/programmatically-creating-a-codepen/  (a work in progress).

**Comment by mickfuzz** [comment]
That sounds really promising. 

This process is complicated a bit by a few factors, 

- Using internally referenced or externally referenced images resources in projects
- Explicitly using HTML in Codepen or not as a game frame (I tend not to, and just use the js tab) 
- Using the Codepen interface to link to js resources, or replicating that  in a script call to a CDN js library in the HTML

**Comment by davegoopot** [comment]
Let's use Glitch instead of CodePen.
