### ISSUE TITLE
Use Glitch instead of CodePen for remixable game examples

### ISSUE THREAD

**Issue by mickfuzz** [webgameclubs/edlab-gamemakers-club#19]
Proposal to use Glitch for better Git integration 

https://youtu.be/aWvTqHNDi_Q

**Comment by davegoopot** [comment]
Working on running an example through on Glitch.

I'm taking notes here: https://davepotts.software/2018/09/06/phaser-game-running-from-glitch/

**Comment by mickfuzz** [comment]
Yes this is looking pretty good isn't it. 
I've done a similar test but wanted to see how images came in. 
first here with a complex project but it failed and the logs don't share a lot 
https://glitch.com/~mickfuzz-glitchtest

But then here with a project with just one image and it works well
https://glitch.com/edit/#!/mickfuzz-glitchtest-1?path=index.html:1:0

I can see this working well for project which are updated via git, and which serve as a base for remixes too, as users can add assets to glitch and then copy the URL to use in the project.

**Comment by davegoopot** [comment]
After some experimentation (written up at https://davepotts.software/2018/09/06/phaser-game-running-from-glitch/ ) I'm thinking the Glitch.com asset update problem is big enough to rule them out. It is just too confusing to a beginner that they have updated an image, loaded it to Glitch.com, but the image has not updated in their app.

What do you think @mickfuzz ?

**Comment by mickfuzz** [comment]
If we think of Glitch as a code playground for beginner users then I actually think this won't be too much of a problem as long as we can get the The GH --> Glitch process working well. 

I'm thinking that a beginner user won't be reimporting their game back into github, and that for the kind of game contributor that might chip in to this project they would be likely to be doing their updates and development locally rather than on glitch. 

The asset uploading on Glitch, while hard to get to look like a locally referenced file, if you don't worry about that, then well it's pretty straightforward, drag into the asset window, and click on it to copy the url to the clipboard, and then paste it into the right place.

This would be similar to what they might have already met doing activities like this one, which beginners were fine with at workshops I've done recently. 
http://write.flossmanuals.net/learn-javascript-with-phaser/jumping-right-in/

For intermediate users then I think it is worth bumping them up to local development in Brackets or similar and teaching how to use Github too. 

I do think it is worth trying out a bit more some relatively complex projects to test the limits of what Glitch can work with.

**Comment by davegoopot** [comment]
So I've hit the next wrinkle in getting Glitch<->GitHub integration working: Glitch import and export won't handle sub-directories. I'm thinking this means we pull out individual games into separate git repos under a single "webgamesclubs" organisation. This probably is a good thing since it isolates any updates in the game to which they apply.

The problem in more detail is that I can't say to Glitch to synchronise with the sub-directory at `edlab-gamemakers-club/games/simple-game-to-edit/`. Rather you must synchronise the whole repo in one go.

@mickfuzz what do you think about splitting games into separate repos?

**Comment by mickfuzz** [comment]
About separate repos, I think that's ok. I was thinking that that was a good way to go anyway as it would allow game developers a lot of freedom

I was imagining something like using git submodule, but I don't know a lot about git submodules and this article doesn't fill me with joy about them.

https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree
But we could start looking into a good way to do this which I guess would:

* allow game contributors to follow a suggested pattern to create their tutorial phaser games
* is easy for them to flag to us to import somehow as a submodule / subtree etc into a central repo of tutorial games (if this is even needed?)
* is easy for us to promote as distinct git URLs for users to import

Although for the last one, I am imagining if we create a list of games that can be remixed then we'll probably point users to Glitch projects which can be remixed, rather than to git URLs that can be imported, as I think the former would be easier to explain, no?

**Comment by davegoopot** [comment]
My previous experience says avoid submodules. We tried it for a CoderDojo project and it was *really* confusing. Just simple links in documentation to other repos work much better.

Also I agree about giving links to Glitch projects rather than GitHub URLs.

I'm going to have a go making a repo for your https://codepen.io/mrmick/pen/wXMMXR game if that's okay with you. I'll port it so that it works in Glitch and I can pull together the steps for GitHub<->Glitch interaction.

**Comment by davegoopot** [comment]
Wow that was easy. I'll write up more later but for now see:

https://github.com/davegoopot/simple_game_to_edit
https://simple-game-to-edit.glitch.me/
https://glitch.com/edit/#!/simple-game-to-edit

**Comment by davegoopot** [comment]
Here's my write up of how this can work. What do you think @mickfuzz ?

https://wordpress.com/post/davepotts.software/144

**Comment by mickfuzz** [comment]
Is that this one?
https://davepotts.software/2018/09/15/glitch-and-github-workflow/
Thanks

**Comment by mickfuzz** [comment]
This looks great. I do think that it is very interesting that there is a chance to fork and then remerge a project using glitch. This actually could be a good introduction to the use of Git for beginners. 

I'll close this and open another issue here about implementing it in documentation -  #22
