### ISSUE TITLE
Would you create a webgameclubs/simple-game-to-edit repo?

### ISSUE THREAD

**Issue by davegoopot** [webgameclubs/edlab-gamemakers-club#21]
Hi @mickfuzz , would you be okay to create webgameclubs/simple-game-to-edit as a fork of webgameclubs/simple-game-to-edit ? First example of Glitch and GitHub.

Thank you, Dave.

**Comment by mickfuzz** [comment]
Yes, sure I've given you owner rights the group as well as this repo. It might be worth looking at this updated project, as I think it gives more scope for editing. 
https://codepen.io/mrmick/pen/MXNqqY?editors=0010

Thanks!

**Comment by davegoopot** [comment]
I've exported https://codepen.io/mrmick/pen/MXNqqY?editors=0010 into https://github.com/webgameclubs/simple-game-to-edit
