### ISSUE TITLE
Change Wiki Home Page to Reference Glitch

### ISSUE THREAD

**Issue by davegoopot** [webgameclubs/edlab-gamemakers-club#25]
https://github.com/webgameclubs/edlab-gamemakers-club/wiki needs updating so the examples are in Glitch rather than Thimble.

**Comment by mickfuzz** [comment]
I've moved the Games mentions out of this wiki page. I've also moved the references further up the page of the README.

**Comment by davegoopot** [comment]
I'll close this off. Always a work in progress, but looks much better after your edit.

**Comment by mickfuzz** [comment]
I've also updated that page to point back to here https://github.com/webgameclubs/edlab-gamemakers-club for Glitch starter games.
