### ISSUE TITLE
Link to Drama Practitioners on README Page Gives 404

### ISSUE THREAD

**Issue by davegoopot** [webgameclubs/edlab-gamemakers-club#27]
The link "Drama Practioners" at the bottom of the "Getting involved in the Clubs and our Resource" section of the README.md file is broken.

**Comment by mickfuzz** [comment]
Thanks!
I've simplified the project a bit by removing that and some of the other streams. I do think less is more for this project now.

I'm also thinking that focusing on getting more participation on the resource creation using this hub is the priority for the mo, and that linking with existing outlets for delivery coder dojo, code club etc is better than trying to co-ordinate that.
