### ISSUE TITLE
Try to move as much data as possible about volunteering and making games OFF of the wiki

### ISSUE THREAD

**Issue by mickfuzz** [webgameclubs/edlab-gamemakers-club#31]
This project site is confusing as there is duplicate material on md pages and in the wiki. 

The reason for doing this no longer holds water, so where ever possible move data OFF the wiki, and simplify the information to make this a Hub for beginner game making resources.

**Comment by davegoopot** [comment]
@mickfuzz should I leave you to updates to the docs and stop updating the wiki?
