### ISSUE TITLE
Simple Code Standards and Linting

### ISSUE THREAD

**Issue by davegoopot** [webgameclubs/edlab-gamemakers-club#33]
Can we pick some simple coding standards and have an easy way to lint files for compliance?

**Comment by davegoopot** [comment]
@mickfuzz How about this as a starting point:

1) Code standards = https://www.w3schools.com/js/js_conventions.asp
2) Linter = copy and paste your code into https://www.jslint.com/

**Comment by davegoopot** [comment]
...but...on https://www.jslint.com/ you have to change the default to "Tolerate long lines" or else it complains about all those data URLs :)

**Comment by davegoopot** [comment]
...and "Tolerate for statement. Might be going off this idea. Will press on for now.

**Comment by mickfuzz** [comment]
I'm linting in Brackets - the default there seems more forgiving. 
I'll share a linted example when I'm done

**Comment by mickfuzz** [comment]
I'm starting to be pretty happy with what this process has created at https://hazards-enemies-vlinted.glitch.me/

Some questions. 
jslint pushes you to declare variables at the start of the function on one line. e.g.

`playState.create = function () {
    //list the variables used only by the create function
    var ground, platform1, platform2, platform3, hazard1, enemy1, tween1, coin, i;`

I've broken that rule for the global variables at the start making a difference between variables that users can hack, and others. 
I've also move variables only used by the create function to be declare in the first line there. I think this could be a good practice here perhaps? And avoids the long list issue.

**Comment by davegoopot** [comment]
Yeah JSLint isn't going to work for this. Worst problem is for

```
    takeCoin: function (player, coin) {
        coin.kill();
        win.play();

    },
```

It reported player not used, but you can't remove it as it is the first param of the arcade.overlap function that calls it. 

Is Brackets a node thing or is there an online version?

I'm going to submit a PR to the simple game with some linting done. Let me know if you think it is too much. Happy to back off from the number of checks if not helpful

**Comment by davegoopot** [comment]
What do you think of this: https://github.com/webgameclubs/simple-game-to-edit/pull/5
